// <auto-generated />
using System;
using LifeLevel.Api.Infrastructure.Persistence;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;

#nullable disable

namespace LifeLevel.Api.Migrations
{
    [DbContext(typeof(AppDbContext))]
    [Migration("20260328072418_AddCharacterSetup")]
    partial class AddCharacterSetup
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "9.0.3")
                .HasAnnotation("Relational:MaxIdentifierLength", 63);

            NpgsqlModelBuilderExtensions.UseIdentityByDefaultColumns(modelBuilder);

            modelBuilder.Entity("LifeLevel.Api.Domain.Entities.Activity", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<int>("AgiGained")
                        .HasColumnType("integer");

                    b.Property<int>("Calories")
                        .HasColumnType("integer");

                    b.Property<Guid>("CharacterId")
                        .HasColumnType("uuid");

                    b.Property<double>("DistanceKm")
                        .HasColumnType("double precision");

                    b.Property<int>("DurationMinutes")
                        .HasColumnType("integer");

                    b.Property<int>("EndGained")
                        .HasColumnType("integer");

                    b.Property<int>("FlxGained")
                        .HasColumnType("integer");

                    b.Property<int?>("HeartRateAvg")
                        .HasColumnType("integer");

                    b.Property<DateTime>("LoggedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<int>("StaGained")
                        .HasColumnType("integer");

                    b.Property<int>("StrGained")
                        .HasColumnType("integer");

                    b.Property<int>("Type")
                        .HasColumnType("integer");

                    b.Property<long>("XpGained")
                        .HasColumnType("bigint");

                    b.HasKey("Id");

                    b.HasIndex("CharacterId");

                    b.ToTable("Activities");
                });

            modelBuilder.Entity("LifeLevel.Api.Domain.Entities.Character", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<int>("Agility")
                        .HasColumnType("integer");

                    b.Property<string>("AvatarEmoji")
                        .HasColumnType("text");

                    b.Property<Guid?>("ClassId")
                        .HasColumnType("uuid");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<int>("Endurance")
                        .HasColumnType("integer");

                    b.Property<int>("Flexibility")
                        .HasColumnType("integer");

                    b.Property<bool>("IsSetupComplete")
                        .HasColumnType("boolean");

                    b.Property<int>("Level")
                        .HasColumnType("integer");

                    b.Property<int>("Rank")
                        .HasColumnType("integer");

                    b.Property<int>("Stamina")
                        .HasColumnType("integer");

                    b.Property<int>("Strength")
                        .HasColumnType("integer");

                    b.Property<DateTime>("UpdatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<Guid>("UserId")
                        .HasColumnType("uuid");

                    b.Property<long>("Xp")
                        .HasColumnType("bigint");

                    b.HasKey("Id");

                    b.HasIndex("ClassId");

                    b.HasIndex("UserId")
                        .IsUnique();

                    b.ToTable("Characters");
                });

            modelBuilder.Entity("LifeLevel.Api.Domain.Entities.CharacterClass", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<float>("AgiMultiplier")
                        .HasColumnType("real");

                    b.Property<string>("Description")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("Emoji")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<float>("EndMultiplier")
                        .HasColumnType("real");

                    b.Property<float>("FlxMultiplier")
                        .HasColumnType("real");

                    b.Property<bool>("IsActive")
                        .HasColumnType("boolean");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<float>("StaMultiplier")
                        .HasColumnType("real");

                    b.Property<float>("StrMultiplier")
                        .HasColumnType("real");

                    b.Property<string>("Tagline")
                        .IsRequired()
                        .HasColumnType("text");

                    b.HasKey("Id");

                    b.HasIndex("Name")
                        .IsUnique();

                    b.ToTable("CharacterClasses");

                    b.HasData(
                        new
                        {
                            Id = new Guid("aaaaaaaa-0001-0000-0000-000000000000"),
                            AgiMultiplier = 1f,
                            Description = "Master of raw power. Gym sessions and heavy lifts are your domain.",
                            Emoji = "⚔️",
                            EndMultiplier = 1f,
                            FlxMultiplier = 1f,
                            IsActive = true,
                            Name = "Warrior",
                            StaMultiplier = 1.2f,
                            StrMultiplier = 1.3f,
                            Tagline = "Lift heavy. Hit harder."
                        },
                        new
                        {
                            Id = new Guid("aaaaaaaa-0002-0000-0000-000000000000"),
                            AgiMultiplier = 1.2f,
                            Description = "Born to endure the long road. Running and cycling are your strengths.",
                            Emoji = "🏹",
                            EndMultiplier = 1.3f,
                            FlxMultiplier = 1f,
                            IsActive = true,
                            Name = "Ranger",
                            StaMultiplier = 1f,
                            StrMultiplier = 1f,
                            Tagline = "Run far. Run fast."
                        },
                        new
                        {
                            Id = new Guid("aaaaaaaa-0003-0000-0000-000000000000"),
                            AgiMultiplier = 1f,
                            Description = "Seeker of balance and flow. Yoga and flexibility training are your path.",
                            Emoji = "🧘",
                            EndMultiplier = 1f,
                            FlxMultiplier = 1.4f,
                            IsActive = true,
                            Name = "Mystic",
                            StaMultiplier = 1.2f,
                            StrMultiplier = 1f,
                            Tagline = "Bend. Don't break."
                        },
                        new
                        {
                            Id = new Guid("aaaaaaaa-0004-0000-0000-000000000000"),
                            AgiMultiplier = 1f,
                            Description = "Immovable. Unstoppable. All-round athlete with iron stamina.",
                            Emoji = "🛡️",
                            EndMultiplier = 1.1f,
                            FlxMultiplier = 1f,
                            IsActive = true,
                            Name = "Sentinel",
                            StaMultiplier = 1.4f,
                            StrMultiplier = 1f,
                            Tagline = "Outlast everything."
                        });
                });

            modelBuilder.Entity("LifeLevel.Api.Domain.Entities.User", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("Email")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("PasswordHash")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("Username")
                        .IsRequired()
                        .HasColumnType("text");

                    b.HasKey("Id");

                    b.HasIndex("Email")
                        .IsUnique();

                    b.HasIndex("Username")
                        .IsUnique();

                    b.ToTable("Users");
                });

            modelBuilder.Entity("LifeLevel.Api.Domain.Entities.UserRingItem", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<string>("ItemType")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<int>("SortOrder")
                        .HasColumnType("integer");

                    b.Property<Guid>("UserId")
                        .HasColumnType("uuid");

                    b.HasKey("Id");

                    b.HasIndex("UserId");

                    b.ToTable("UserRingItems");
                });

            modelBuilder.Entity("LifeLevel.Api.Domain.Entities.Activity", b =>
                {
                    b.HasOne("LifeLevel.Api.Domain.Entities.Character", "Character")
                        .WithMany("Activities")
                        .HasForeignKey("CharacterId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Character");
                });

            modelBuilder.Entity("LifeLevel.Api.Domain.Entities.Character", b =>
                {
                    b.HasOne("LifeLevel.Api.Domain.Entities.CharacterClass", "Class")
                        .WithMany("Characters")
                        .HasForeignKey("ClassId");

                    b.HasOne("LifeLevel.Api.Domain.Entities.User", "User")
                        .WithOne("Character")
                        .HasForeignKey("LifeLevel.Api.Domain.Entities.Character", "UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Class");

                    b.Navigation("User");
                });

            modelBuilder.Entity("LifeLevel.Api.Domain.Entities.UserRingItem", b =>
                {
                    b.HasOne("LifeLevel.Api.Domain.Entities.User", "User")
                        .WithMany("RingItems")
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("User");
                });

            modelBuilder.Entity("LifeLevel.Api.Domain.Entities.Character", b =>
                {
                    b.Navigation("Activities");
                });

            modelBuilder.Entity("LifeLevel.Api.Domain.Entities.CharacterClass", b =>
                {
                    b.Navigation("Characters");
                });

            modelBuilder.Entity("LifeLevel.Api.Domain.Entities.User", b =>
                {
                    b.Navigation("Character");

                    b.Navigation("RingItems");
                });
#pragma warning restore 612, 618
        }
    }
}
