// <auto-generated />
using System;
using LifeLevel.Api.Infrastructure.Persistence;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;

#nullable disable

namespace LifeLevel.Api.Migrations
{
    [DbContext(typeof(AppDbContext))]
    [Migration("20260330221640_AddStravaConnection")]
    partial class AddStravaConnection
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "9.0.3")
                .HasAnnotation("Relational:MaxIdentifierLength", 63);

            NpgsqlModelBuilderExtensions.UseIdentityByDefaultColumns(modelBuilder);

            modelBuilder.Entity("LifeLevel.Modules.Activity.Domain.Entities.Activity", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<int>("AgiGained")
                        .HasColumnType("integer");

                    b.Property<int>("Calories")
                        .HasColumnType("integer");

                    b.Property<Guid>("CharacterId")
                        .HasColumnType("uuid");

                    b.Property<double>("DistanceKm")
                        .HasColumnType("double precision");

                    b.Property<int>("DurationMinutes")
                        .HasColumnType("integer");

                    b.Property<int>("EndGained")
                        .HasColumnType("integer");

                    b.Property<string>("ExternalId")
                        .HasMaxLength(200)
                        .HasColumnType("character varying(200)");

                    b.Property<int>("FlxGained")
                        .HasColumnType("integer");

                    b.Property<int?>("HeartRateAvg")
                        .HasColumnType("integer");

                    b.Property<DateTime>("LoggedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<int>("StaGained")
                        .HasColumnType("integer");

                    b.Property<int>("StrGained")
                        .HasColumnType("integer");

                    b.Property<string>("Type")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<long>("XpGained")
                        .HasColumnType("bigint");

                    b.HasKey("Id");

                    b.HasIndex("CharacterId", "ExternalId")
                        .IsUnique()
                        .HasFilter("\"ExternalId\" IS NOT NULL");

                    b.ToTable("Activities");
                });

            modelBuilder.Entity("LifeLevel.Modules.Adventure.Dungeons.Domain.Entities.Crossroads", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<Guid>("NodeId")
                        .HasColumnType("uuid");

                    b.HasKey("Id");

                    b.HasIndex("NodeId")
                        .IsUnique();

                    b.ToTable("Crossroads");
                });

            modelBuilder.Entity("LifeLevel.Modules.Adventure.Dungeons.Domain.Entities.CrossroadsPath", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<string>("AdditionalRequirement")
                        .HasColumnType("text");

                    b.Property<Guid>("CrossroadsId")
                        .HasColumnType("uuid");

                    b.Property<string>("Difficulty")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<double>("DistanceKm")
                        .HasColumnType("double precision");

                    b.Property<int>("EstimatedDays")
                        .HasColumnType("integer");

                    b.Property<Guid?>("LeadsToNodeId")
                        .HasColumnType("uuid");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<int>("RewardXp")
                        .HasColumnType("integer");

                    b.HasKey("Id");

                    b.HasIndex("CrossroadsId");

                    b.HasIndex("LeadsToNodeId");

                    b.ToTable("CrossroadsPaths");
                });

            modelBuilder.Entity("LifeLevel.Modules.Adventure.Dungeons.Domain.Entities.DungeonFloor", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<Guid>("DungeonPortalId")
                        .HasColumnType("uuid");

                    b.Property<int>("FloorNumber")
                        .HasColumnType("integer");

                    b.Property<string>("RequiredActivity")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<int>("RequiredMinutes")
                        .HasColumnType("integer");

                    b.Property<int>("RewardXp")
                        .HasColumnType("integer");

                    b.HasKey("Id");

                    b.HasIndex("DungeonPortalId");

                    b.ToTable("DungeonFloors");
                });

            modelBuilder.Entity("LifeLevel.Modules.Adventure.Dungeons.Domain.Entities.DungeonPortal", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<Guid>("NodeId")
                        .HasColumnType("uuid");

                    b.Property<int>("TotalFloors")
                        .HasColumnType("integer");

                    b.HasKey("Id");

                    b.HasIndex("NodeId")
                        .IsUnique();

                    b.ToTable("DungeonPortals");
                });

            modelBuilder.Entity("LifeLevel.Modules.Adventure.Dungeons.Domain.Entities.UserCrossroadsState", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<DateTime?>("ChosenAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<Guid?>("ChosenPathId")
                        .HasColumnType("uuid");

                    b.Property<Guid>("CrossroadsId")
                        .HasColumnType("uuid");

                    b.Property<Guid>("UserId")
                        .HasColumnType("uuid");

                    b.Property<Guid>("UserMapProgressId")
                        .HasColumnType("uuid");

                    b.HasKey("Id");

                    b.HasIndex("ChosenPathId");

                    b.HasIndex("CrossroadsId");

                    b.HasIndex("UserId");

                    b.HasIndex("UserMapProgressId");

                    b.ToTable("UserCrossroadsStates");
                });

            modelBuilder.Entity("LifeLevel.Modules.Adventure.Dungeons.Domain.Entities.UserDungeonState", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<int>("CurrentFloor")
                        .HasColumnType("integer");

                    b.Property<DateTime?>("DiscoveredAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<Guid>("DungeonPortalId")
                        .HasColumnType("uuid");

                    b.Property<bool>("IsDiscovered")
                        .HasColumnType("boolean");

                    b.Property<Guid>("UserId")
                        .HasColumnType("uuid");

                    b.Property<Guid>("UserMapProgressId")
                        .HasColumnType("uuid");

                    b.HasKey("Id");

                    b.HasIndex("DungeonPortalId");

                    b.HasIndex("UserId");

                    b.HasIndex("UserMapProgressId");

                    b.ToTable("UserDungeonStates");
                });

            modelBuilder.Entity("LifeLevel.Modules.Adventure.Encounters.Domain.Entities.Boss", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<string>("Icon")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<bool>("IsMini")
                        .HasColumnType("boolean");

                    b.Property<int>("MaxHp")
                        .HasColumnType("integer");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<Guid>("NodeId")
                        .HasColumnType("uuid");

                    b.Property<int>("RewardXp")
                        .HasColumnType("integer");

                    b.Property<int>("TimerDays")
                        .HasColumnType("integer");

                    b.HasKey("Id");

                    b.HasIndex("NodeId")
                        .IsUnique();

                    b.ToTable("Bosses");
                });

            modelBuilder.Entity("LifeLevel.Modules.Adventure.Encounters.Domain.Entities.Chest", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<Guid>("NodeId")
                        .HasColumnType("uuid");

                    b.Property<string>("Rarity")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<int>("RewardXp")
                        .HasColumnType("integer");

                    b.HasKey("Id");

                    b.HasIndex("NodeId")
                        .IsUnique();

                    b.ToTable("Chests");
                });

            modelBuilder.Entity("LifeLevel.Modules.Adventure.Encounters.Domain.Entities.UserBossState", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<Guid>("BossId")
                        .HasColumnType("uuid");

                    b.Property<DateTime?>("DefeatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<int>("HpDealt")
                        .HasColumnType("integer");

                    b.Property<bool>("IsDefeated")
                        .HasColumnType("boolean");

                    b.Property<bool>("IsExpired")
                        .HasColumnType("boolean");

                    b.Property<DateTime?>("StartedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<Guid>("UserId")
                        .HasColumnType("uuid");

                    b.Property<Guid>("UserMapProgressId")
                        .HasColumnType("uuid");

                    b.HasKey("Id");

                    b.HasIndex("BossId");

                    b.HasIndex("UserId");

                    b.HasIndex("UserMapProgressId");

                    b.ToTable("UserBossStates");
                });

            modelBuilder.Entity("LifeLevel.Modules.Adventure.Encounters.Domain.Entities.UserChestState", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<Guid>("ChestId")
                        .HasColumnType("uuid");

                    b.Property<DateTime?>("CollectedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<bool>("IsCollected")
                        .HasColumnType("boolean");

                    b.Property<Guid>("UserId")
                        .HasColumnType("uuid");

                    b.Property<Guid>("UserMapProgressId")
                        .HasColumnType("uuid");

                    b.HasKey("Id");

                    b.HasIndex("ChestId");

                    b.HasIndex("UserId");

                    b.HasIndex("UserMapProgressId");

                    b.ToTable("UserChestStates");
                });

            modelBuilder.Entity("LifeLevel.Modules.Character.Domain.Entities.Character", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<int>("Agility")
                        .HasColumnType("integer");

                    b.Property<int>("AvailableStatPoints")
                        .HasColumnType("integer");

                    b.Property<string>("AvatarEmoji")
                        .HasColumnType("text");

                    b.Property<Guid?>("ClassId")
                        .HasColumnType("uuid");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<int>("Endurance")
                        .HasColumnType("integer");

                    b.Property<int>("Flexibility")
                        .HasColumnType("integer");

                    b.Property<bool>("IsSetupComplete")
                        .HasColumnType("boolean");

                    b.Property<int>("Level")
                        .HasColumnType("integer");

                    b.Property<int>("Rank")
                        .HasColumnType("integer");

                    b.Property<int>("Stamina")
                        .HasColumnType("integer");

                    b.Property<int>("Strength")
                        .HasColumnType("integer");

                    b.Property<DateTime>("UpdatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<Guid>("UserId")
                        .HasColumnType("uuid");

                    b.Property<long>("Xp")
                        .HasColumnType("bigint");

                    b.HasKey("Id");

                    b.HasIndex("ClassId");

                    b.HasIndex("UserId")
                        .IsUnique();

                    b.ToTable("Characters");
                });

            modelBuilder.Entity("LifeLevel.Modules.Character.Domain.Entities.CharacterClass", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<float>("AgiMultiplier")
                        .HasColumnType("real");

                    b.Property<string>("Description")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("Emoji")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<float>("EndMultiplier")
                        .HasColumnType("real");

                    b.Property<float>("FlxMultiplier")
                        .HasColumnType("real");

                    b.Property<bool>("IsActive")
                        .HasColumnType("boolean");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<float>("StaMultiplier")
                        .HasColumnType("real");

                    b.Property<float>("StrMultiplier")
                        .HasColumnType("real");

                    b.Property<string>("Tagline")
                        .IsRequired()
                        .HasColumnType("text");

                    b.HasKey("Id");

                    b.HasIndex("Name")
                        .IsUnique();

                    b.ToTable("CharacterClasses");

                    b.HasData(
                        new
                        {
                            Id = new Guid("aaaaaaaa-0001-0000-0000-000000000000"),
                            AgiMultiplier = 1f,
                            Description = "Master of raw power. Gym sessions and heavy lifts are your domain.",
                            Emoji = "⚔️",
                            EndMultiplier = 1f,
                            FlxMultiplier = 1f,
                            IsActive = true,
                            Name = "Warrior",
                            StaMultiplier = 1.2f,
                            StrMultiplier = 1.3f,
                            Tagline = "Lift heavy. Hit harder."
                        },
                        new
                        {
                            Id = new Guid("aaaaaaaa-0002-0000-0000-000000000000"),
                            AgiMultiplier = 1.2f,
                            Description = "Born to endure the long road. Running and cycling are your strengths.",
                            Emoji = "🏹",
                            EndMultiplier = 1.3f,
                            FlxMultiplier = 1f,
                            IsActive = true,
                            Name = "Ranger",
                            StaMultiplier = 1f,
                            StrMultiplier = 1f,
                            Tagline = "Run far. Run fast."
                        },
                        new
                        {
                            Id = new Guid("aaaaaaaa-0003-0000-0000-000000000000"),
                            AgiMultiplier = 1f,
                            Description = "Seeker of balance and flow. Yoga and flexibility training are your path.",
                            Emoji = "🧘",
                            EndMultiplier = 1f,
                            FlxMultiplier = 1.4f,
                            IsActive = true,
                            Name = "Mystic",
                            StaMultiplier = 1.2f,
                            StrMultiplier = 1f,
                            Tagline = "Bend. Don't break."
                        },
                        new
                        {
                            Id = new Guid("aaaaaaaa-0004-0000-0000-000000000000"),
                            AgiMultiplier = 1f,
                            Description = "Immovable. Unstoppable. All-round athlete with iron stamina.",
                            Emoji = "🛡️",
                            EndMultiplier = 1.1f,
                            FlxMultiplier = 1f,
                            IsActive = true,
                            Name = "Sentinel",
                            StaMultiplier = 1.4f,
                            StrMultiplier = 1f,
                            Tagline = "Outlast everything."
                        });
                });

            modelBuilder.Entity("LifeLevel.Modules.Character.Domain.Entities.XpHistoryEntry", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<Guid>("CharacterId")
                        .HasColumnType("uuid");

                    b.Property<string>("Description")
                        .IsRequired()
                        .HasMaxLength(256)
                        .HasColumnType("character varying(256)");

                    b.Property<DateTime>("EarnedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("Source")
                        .IsRequired()
                        .HasMaxLength(64)
                        .HasColumnType("character varying(64)");

                    b.Property<string>("SourceEmoji")
                        .IsRequired()
                        .HasMaxLength(16)
                        .HasColumnType("character varying(16)");

                    b.Property<long>("Xp")
                        .HasColumnType("bigint");

                    b.HasKey("Id");

                    b.HasIndex("CharacterId");

                    b.ToTable("XpHistoryEntries");
                });

            modelBuilder.Entity("LifeLevel.Modules.Identity.Domain.Entities.User", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("Email")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("PasswordHash")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("Role")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("Username")
                        .IsRequired()
                        .HasColumnType("text");

                    b.HasKey("Id");

                    b.HasIndex("Email")
                        .IsUnique();

                    b.HasIndex("Username")
                        .IsUnique();

                    b.ToTable("Users");
                });

            modelBuilder.Entity("LifeLevel.Modules.Identity.Domain.Entities.UserRingItem", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<string>("ItemType")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<int>("SortOrder")
                        .HasColumnType("integer");

                    b.Property<Guid>("UserId")
                        .HasColumnType("uuid");

                    b.HasKey("Id");

                    b.HasIndex("UserId");

                    b.ToTable("UserRingItems");
                });

            modelBuilder.Entity("LifeLevel.Modules.Integrations.Domain.Entities.ExternalActivityRecord", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<DateTime>("ActivityStartTime")
                        .HasColumnType("timestamp with time zone");

                    b.Property<Guid>("CharacterId")
                        .HasColumnType("uuid");

                    b.Property<string>("ExternalId")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("character varying(200)");

                    b.Property<Guid?>("ImportedActivityId")
                        .HasColumnType("uuid");

                    b.Property<string>("Provider")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)");

                    b.Property<DateTime>("SyncedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<bool>("WasImported")
                        .HasColumnType("boolean");

                    b.HasKey("Id");

                    b.HasIndex("CharacterId", "Provider", "ExternalId")
                        .IsUnique();

                    b.ToTable("ExternalActivityRecords");
                });

            modelBuilder.Entity("LifeLevel.Modules.Integrations.Domain.Entities.StravaConnection", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<string>("AccessToken")
                        .IsRequired()
                        .HasMaxLength(500)
                        .HasColumnType("character varying(500)");

                    b.Property<string>("AthleteName")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("character varying(200)");

                    b.Property<DateTime>("ConnectedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<DateTime>("ExpiresAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<bool>("IsActive")
                        .HasColumnType("boolean");

                    b.Property<string>("RefreshToken")
                        .IsRequired()
                        .HasMaxLength(500)
                        .HasColumnType("character varying(500)");

                    b.Property<long>("StravaAthleteId")
                        .HasColumnType("bigint");

                    b.Property<Guid>("UserId")
                        .HasColumnType("uuid");

                    b.HasKey("Id");

                    b.HasIndex("StravaAthleteId")
                        .IsUnique();

                    b.HasIndex("UserId");

                    b.ToTable("StravaConnections");
                });

            modelBuilder.Entity("LifeLevel.Modules.Items.Domain.Entities.CharacterItem", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<DateTime>("AcquiredAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<Guid>("CharacterId")
                        .HasColumnType("uuid");

                    b.Property<bool>("IsEquipped")
                        .HasColumnType("boolean");

                    b.Property<Guid>("ItemId")
                        .HasColumnType("uuid");

                    b.HasKey("Id");

                    b.HasIndex("CharacterId");

                    b.HasIndex("ItemId");

                    b.ToTable("CharacterItems");
                });

            modelBuilder.Entity("LifeLevel.Modules.Items.Domain.Entities.EquipmentSlot", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<Guid>("CharacterId")
                        .HasColumnType("uuid");

                    b.Property<Guid?>("CharacterItemId")
                        .HasColumnType("uuid");

                    b.Property<string>("SlotType")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<DateTime>("UpdatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.HasKey("Id");

                    b.HasIndex("CharacterItemId");

                    b.HasIndex("CharacterId", "SlotType")
                        .IsUnique();

                    b.ToTable("EquipmentSlots");
                });

            modelBuilder.Entity("LifeLevel.Modules.Items.Domain.Entities.Item", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<int>("AgiBonus")
                        .HasColumnType("integer");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("Description")
                        .IsRequired()
                        .HasMaxLength(500)
                        .HasColumnType("character varying(500)");

                    b.Property<int>("EndBonus")
                        .HasColumnType("integer");

                    b.Property<int>("FlxBonus")
                        .HasColumnType("integer");

                    b.Property<string>("Icon")
                        .IsRequired()
                        .HasMaxLength(10)
                        .HasColumnType("character varying(10)");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)");

                    b.Property<string>("Rarity")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("SlotType")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<int>("StaBonus")
                        .HasColumnType("integer");

                    b.Property<int>("StrBonus")
                        .HasColumnType("integer");

                    b.Property<int>("XpBonusPct")
                        .HasColumnType("integer");

                    b.HasKey("Id");

                    b.ToTable("Items");
                });

            modelBuilder.Entity("LifeLevel.Modules.LoginReward.Domain.Entities.LoginReward", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<bool>("ClaimedToday")
                        .HasColumnType("boolean");

                    b.Property<int>("DayInCycle")
                        .HasColumnType("integer");

                    b.Property<DateTime?>("LastClaimedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<int>("TotalLoginDays")
                        .HasColumnType("integer");

                    b.Property<Guid>("UserId")
                        .HasColumnType("uuid");

                    b.HasKey("Id");

                    b.HasIndex("UserId")
                        .IsUnique();

                    b.ToTable("LoginRewards");
                });

            modelBuilder.Entity("LifeLevel.Modules.Map.Domain.Entities.MapEdge", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<double>("DistanceKm")
                        .HasColumnType("double precision");

                    b.Property<Guid>("FromNodeId")
                        .HasColumnType("uuid");

                    b.Property<bool>("IsBidirectional")
                        .HasColumnType("boolean");

                    b.Property<Guid>("ToNodeId")
                        .HasColumnType("uuid");

                    b.HasKey("Id");

                    b.HasIndex("FromNodeId");

                    b.HasIndex("ToNodeId");

                    b.ToTable("MapEdges");
                });

            modelBuilder.Entity("LifeLevel.Modules.Map.Domain.Entities.MapNode", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<string>("Description")
                        .HasColumnType("text");

                    b.Property<string>("Icon")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<bool>("IsHidden")
                        .HasColumnType("boolean");

                    b.Property<bool>("IsStartNode")
                        .HasColumnType("boolean");

                    b.Property<int>("LevelRequirement")
                        .HasColumnType("integer");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<float>("PositionX")
                        .HasColumnType("real");

                    b.Property<float>("PositionY")
                        .HasColumnType("real");

                    b.Property<string>("Region")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<int>("RewardXp")
                        .HasColumnType("integer");

                    b.Property<string>("Type")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<Guid?>("WorldZoneId")
                        .HasColumnType("uuid");

                    b.HasKey("Id");

                    b.HasIndex("WorldZoneId");

                    b.ToTable("MapNodes");
                });

            modelBuilder.Entity("LifeLevel.Modules.Map.Domain.Entities.UserMapProgress", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<Guid?>("CurrentEdgeId")
                        .HasColumnType("uuid");

                    b.Property<Guid>("CurrentNodeId")
                        .HasColumnType("uuid");

                    b.Property<Guid?>("DestinationNodeId")
                        .HasColumnType("uuid");

                    b.Property<double>("DistanceTraveledOnEdge")
                        .HasColumnType("double precision");

                    b.Property<DateTime>("UpdatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<Guid>("UserId")
                        .HasColumnType("uuid");

                    b.HasKey("Id");

                    b.HasIndex("CurrentEdgeId");

                    b.HasIndex("CurrentNodeId");

                    b.HasIndex("DestinationNodeId");

                    b.HasIndex("UserId");

                    b.ToTable("UserMapProgresses");
                });

            modelBuilder.Entity("LifeLevel.Modules.Map.Domain.Entities.UserNodeUnlock", b =>
                {
                    b.Property<Guid>("UserId")
                        .HasColumnType("uuid");

                    b.Property<Guid>("MapNodeId")
                        .HasColumnType("uuid");

                    b.Property<DateTime>("UnlockedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<Guid>("UserMapProgressId")
                        .HasColumnType("uuid");

                    b.HasKey("UserId", "MapNodeId");

                    b.HasIndex("MapNodeId");

                    b.HasIndex("UserMapProgressId");

                    b.ToTable("UserNodeUnlocks");
                });

            modelBuilder.Entity("LifeLevel.Modules.Quest.Domain.Entities.Quest", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<string>("Category")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("Description")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<bool>("IsActive")
                        .HasColumnType("boolean");

                    b.Property<string>("RequiredActivity")
                        .HasColumnType("text");

                    b.Property<long>("RewardXp")
                        .HasColumnType("bigint");

                    b.Property<int>("SortOrder")
                        .HasColumnType("integer");

                    b.Property<string>("TargetUnit")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<double?>("TargetValue")
                        .HasColumnType("double precision");

                    b.Property<string>("Title")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("Type")
                        .IsRequired()
                        .HasColumnType("text");

                    b.HasKey("Id");

                    b.ToTable("Quests");

                    b.HasData(
                        new
                        {
                            Id = new Guid("bbbbbbbb-0001-0000-0000-000000000000"),
                            Category = "Duration",
                            Description = "Complete any workout lasting at least 30 minutes.",
                            IsActive = true,
                            RewardXp = 150L,
                            SortOrder = 1,
                            TargetUnit = "minutes",
                            TargetValue = 30.0,
                            Title = "Morning Mover",
                            Type = "Daily"
                        },
                        new
                        {
                            Id = new Guid("bbbbbbbb-0002-0000-0000-000000000000"),
                            Category = "Calories",
                            Description = "Burn at least 300 calories in a single session.",
                            IsActive = true,
                            RewardXp = 200L,
                            SortOrder = 2,
                            TargetUnit = "calories",
                            TargetValue = 300.0,
                            Title = "Calorie Crusher",
                            Type = "Daily"
                        },
                        new
                        {
                            Id = new Guid("bbbbbbbb-0003-0000-0000-000000000000"),
                            Category = "Distance",
                            Description = "Run at least 5 km.",
                            IsActive = true,
                            RequiredActivity = "Running",
                            RewardXp = 250L,
                            SortOrder = 3,
                            TargetUnit = "km",
                            TargetValue = 5.0,
                            Title = "Road Warrior",
                            Type = "Daily"
                        },
                        new
                        {
                            Id = new Guid("bbbbbbbb-0004-0000-0000-000000000000"),
                            Category = "Duration",
                            Description = "Hit the gym for at least 45 minutes.",
                            IsActive = true,
                            RequiredActivity = "Gym",
                            RewardXp = 200L,
                            SortOrder = 4,
                            TargetUnit = "minutes",
                            TargetValue = 45.0,
                            Title = "Iron Session",
                            Type = "Daily"
                        },
                        new
                        {
                            Id = new Guid("bbbbbbbb-0005-0000-0000-000000000000"),
                            Category = "Duration",
                            Description = "Practice yoga for at least 30 minutes.",
                            IsActive = true,
                            RequiredActivity = "Yoga",
                            RewardXp = 150L,
                            SortOrder = 5,
                            TargetUnit = "minutes",
                            TargetValue = 30.0,
                            Title = "Zen Master",
                            Type = "Daily"
                        },
                        new
                        {
                            Id = new Guid("bbbbbbbb-0006-0000-0000-000000000000"),
                            Category = "Duration",
                            Description = "Run for at least 30 minutes.",
                            IsActive = true,
                            RequiredActivity = "Running",
                            RewardXp = 175L,
                            SortOrder = 6,
                            TargetUnit = "minutes",
                            TargetValue = 30.0,
                            Title = "Endurance Push",
                            Type = "Daily"
                        },
                        new
                        {
                            Id = new Guid("bbbbbbbb-0007-0000-0000-000000000000"),
                            Category = "Workouts",
                            Description = "Complete 3 workouts this week.",
                            IsActive = true,
                            RewardXp = 500L,
                            SortOrder = 1,
                            TargetUnit = "workouts",
                            TargetValue = 3.0,
                            Title = "Triple Threat",
                            Type = "Weekly"
                        },
                        new
                        {
                            Id = new Guid("bbbbbbbb-0008-0000-0000-000000000000"),
                            Category = "Distance",
                            Description = "Run a total of 10 km this week.",
                            IsActive = true,
                            RequiredActivity = "Running",
                            RewardXp = 600L,
                            SortOrder = 2,
                            TargetUnit = "km",
                            TargetValue = 10.0,
                            Title = "Road Runner",
                            Type = "Weekly"
                        },
                        new
                        {
                            Id = new Guid("bbbbbbbb-0009-0000-0000-000000000000"),
                            Category = "Duration",
                            Description = "Spend at least 90 minutes at the gym this week.",
                            IsActive = true,
                            RequiredActivity = "Gym",
                            RewardXp = 550L,
                            SortOrder = 3,
                            TargetUnit = "minutes",
                            TargetValue = 90.0,
                            Title = "Iron Week",
                            Type = "Weekly"
                        },
                        new
                        {
                            Id = new Guid("bbbbbbbb-0010-0000-0000-000000000000"),
                            Category = "Distance",
                            Description = "Run a total of 10 km across all activities.",
                            IsActive = true,
                            RequiredActivity = "Running",
                            RewardXp = 1000L,
                            SortOrder = 1,
                            TargetUnit = "km",
                            TargetValue = 10.0,
                            Title = "First Steps",
                            Type = "Special"
                        },
                        new
                        {
                            Id = new Guid("bbbbbbbb-0011-0000-0000-000000000000"),
                            Category = "Duration",
                            Description = "Spend 60 minutes climbing.",
                            IsActive = true,
                            RequiredActivity = "Climbing",
                            RewardXp = 1200L,
                            SortOrder = 2,
                            TargetUnit = "minutes",
                            TargetValue = 60.0,
                            Title = "Summit Seeker",
                            Type = "Special"
                        },
                        new
                        {
                            Id = new Guid("bbbbbbbb-0012-0000-0000-000000000000"),
                            Category = "Duration",
                            Description = "Log a total of 500 minutes of any activity.",
                            IsActive = true,
                            RewardXp = 2000L,
                            SortOrder = 3,
                            TargetUnit = "minutes",
                            TargetValue = 500.0,
                            Title = "Endurance Initiate",
                            Type = "Special"
                        });
                });

            modelBuilder.Entity("LifeLevel.Modules.Quest.Domain.Entities.UserQuestProgress", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<DateTime>("AssignedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<bool>("BonusAwarded")
                        .HasColumnType("boolean");

                    b.Property<DateTime?>("CompletedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<double>("CurrentValue")
                        .HasColumnType("double precision");

                    b.Property<DateTime>("ExpiresAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<bool>("IsCompleted")
                        .HasColumnType("boolean");

                    b.Property<Guid>("QuestId")
                        .HasColumnType("uuid");

                    b.Property<bool>("RewardClaimed")
                        .HasColumnType("boolean");

                    b.Property<Guid>("UserId")
                        .HasColumnType("uuid");

                    b.HasKey("Id");

                    b.HasIndex("QuestId");

                    b.HasIndex("UserId");

                    b.ToTable("UserQuestProgress");
                });

            modelBuilder.Entity("LifeLevel.Modules.Streak.Domain.Entities.Streak", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<int>("Current")
                        .HasColumnType("integer");

                    b.Property<DateTime?>("LastActivityDate")
                        .HasColumnType("timestamp with time zone");

                    b.Property<int>("Longest")
                        .HasColumnType("integer");

                    b.Property<bool>("ShieldUsedToday")
                        .HasColumnType("boolean");

                    b.Property<int>("ShieldsAvailable")
                        .HasColumnType("integer");

                    b.Property<int>("ShieldsUsed")
                        .HasColumnType("integer");

                    b.Property<int>("TotalDaysActive")
                        .HasColumnType("integer");

                    b.Property<Guid>("UserId")
                        .HasColumnType("uuid");

                    b.HasKey("Id");

                    b.HasIndex("UserId")
                        .IsUnique();

                    b.ToTable("Streaks");
                });

            modelBuilder.Entity("LifeLevel.Modules.WorldZone.Domain.Entities.UserWorldProgress", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<Guid?>("CurrentEdgeId")
                        .HasColumnType("uuid");

                    b.Property<Guid>("CurrentZoneId")
                        .HasColumnType("uuid");

                    b.Property<Guid?>("DestinationZoneId")
                        .HasColumnType("uuid");

                    b.Property<double>("DistanceTraveledOnEdge")
                        .HasColumnType("double precision");

                    b.Property<DateTime>("UpdatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<Guid>("UserId")
                        .HasColumnType("uuid");

                    b.Property<Guid>("WorldId")
                        .HasColumnType("uuid");

                    b.HasKey("Id");

                    b.HasIndex("CurrentEdgeId");

                    b.HasIndex("CurrentZoneId");

                    b.HasIndex("DestinationZoneId");

                    b.HasIndex("UserId");

                    b.HasIndex("WorldId");

                    b.ToTable("UserWorldProgresses");
                });

            modelBuilder.Entity("LifeLevel.Modules.WorldZone.Domain.Entities.UserZoneUnlock", b =>
                {
                    b.Property<Guid>("UserId")
                        .HasColumnType("uuid");

                    b.Property<Guid>("WorldZoneId")
                        .HasColumnType("uuid");

                    b.Property<DateTime>("UnlockedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<Guid>("UserWorldProgressId")
                        .HasColumnType("uuid");

                    b.HasKey("UserId", "WorldZoneId");

                    b.HasIndex("UserWorldProgressId");

                    b.HasIndex("WorldZoneId");

                    b.ToTable("UserZoneUnlocks");
                });

            modelBuilder.Entity("LifeLevel.Modules.WorldZone.Domain.Entities.World", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<bool>("IsActive")
                        .HasColumnType("boolean");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("text");

                    b.HasKey("Id");

                    b.ToTable("Worlds");
                });

            modelBuilder.Entity("LifeLevel.Modules.WorldZone.Domain.Entities.WorldZone", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<string>("Description")
                        .HasColumnType("text");

                    b.Property<string>("Icon")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<bool>("IsCrossroads")
                        .HasColumnType("boolean");

                    b.Property<bool>("IsHidden")
                        .HasColumnType("boolean");

                    b.Property<bool>("IsStartZone")
                        .HasColumnType("boolean");

                    b.Property<int>("LevelRequirement")
                        .HasColumnType("integer");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<float>("PositionX")
                        .HasColumnType("real");

                    b.Property<float>("PositionY")
                        .HasColumnType("real");

                    b.Property<string>("Region")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<int>("Tier")
                        .HasColumnType("integer");

                    b.Property<double>("TotalDistanceKm")
                        .HasColumnType("double precision");

                    b.Property<int>("TotalXp")
                        .HasColumnType("integer");

                    b.Property<Guid>("WorldId")
                        .HasColumnType("uuid");

                    b.HasKey("Id");

                    b.HasIndex("WorldId");

                    b.ToTable("WorldZones");
                });

            modelBuilder.Entity("LifeLevel.Modules.WorldZone.Domain.Entities.WorldZoneEdge", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<double>("DistanceKm")
                        .HasColumnType("double precision");

                    b.Property<Guid>("FromZoneId")
                        .HasColumnType("uuid");

                    b.Property<bool>("IsBidirectional")
                        .HasColumnType("boolean");

                    b.Property<Guid>("ToZoneId")
                        .HasColumnType("uuid");

                    b.HasKey("Id");

                    b.HasIndex("FromZoneId");

                    b.HasIndex("ToZoneId");

                    b.ToTable("WorldZoneEdges");
                });

            modelBuilder.Entity("LifeLevel.Modules.Activity.Domain.Entities.Activity", b =>
                {
                    b.HasOne("LifeLevel.Modules.Character.Domain.Entities.Character", null)
                        .WithMany()
                        .HasForeignKey("CharacterId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("LifeLevel.Modules.Adventure.Dungeons.Domain.Entities.Crossroads", b =>
                {
                    b.HasOne("LifeLevel.Modules.Map.Domain.Entities.MapNode", null)
                        .WithOne()
                        .HasForeignKey("LifeLevel.Modules.Adventure.Dungeons.Domain.Entities.Crossroads", "NodeId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("LifeLevel.Modules.Adventure.Dungeons.Domain.Entities.CrossroadsPath", b =>
                {
                    b.HasOne("LifeLevel.Modules.Adventure.Dungeons.Domain.Entities.Crossroads", "Crossroads")
                        .WithMany("Paths")
                        .HasForeignKey("CrossroadsId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("LifeLevel.Modules.Map.Domain.Entities.MapNode", null)
                        .WithMany()
                        .HasForeignKey("LeadsToNodeId")
                        .OnDelete(DeleteBehavior.Restrict);

                    b.Navigation("Crossroads");
                });

            modelBuilder.Entity("LifeLevel.Modules.Adventure.Dungeons.Domain.Entities.DungeonFloor", b =>
                {
                    b.HasOne("LifeLevel.Modules.Adventure.Dungeons.Domain.Entities.DungeonPortal", "DungeonPortal")
                        .WithMany("Floors")
                        .HasForeignKey("DungeonPortalId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("DungeonPortal");
                });

            modelBuilder.Entity("LifeLevel.Modules.Adventure.Dungeons.Domain.Entities.DungeonPortal", b =>
                {
                    b.HasOne("LifeLevel.Modules.Map.Domain.Entities.MapNode", null)
                        .WithOne()
                        .HasForeignKey("LifeLevel.Modules.Adventure.Dungeons.Domain.Entities.DungeonPortal", "NodeId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("LifeLevel.Modules.Adventure.Dungeons.Domain.Entities.UserCrossroadsState", b =>
                {
                    b.HasOne("LifeLevel.Modules.Adventure.Dungeons.Domain.Entities.CrossroadsPath", "ChosenPath")
                        .WithMany()
                        .HasForeignKey("ChosenPathId")
                        .OnDelete(DeleteBehavior.Restrict);

                    b.HasOne("LifeLevel.Modules.Adventure.Dungeons.Domain.Entities.Crossroads", "Crossroads")
                        .WithMany("UserStates")
                        .HasForeignKey("CrossroadsId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("LifeLevel.Modules.Identity.Domain.Entities.User", null)
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("LifeLevel.Modules.Map.Domain.Entities.UserMapProgress", null)
                        .WithMany()
                        .HasForeignKey("UserMapProgressId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("ChosenPath");

                    b.Navigation("Crossroads");
                });

            modelBuilder.Entity("LifeLevel.Modules.Adventure.Dungeons.Domain.Entities.UserDungeonState", b =>
                {
                    b.HasOne("LifeLevel.Modules.Adventure.Dungeons.Domain.Entities.DungeonPortal", "DungeonPortal")
                        .WithMany("UserStates")
                        .HasForeignKey("DungeonPortalId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("LifeLevel.Modules.Identity.Domain.Entities.User", null)
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("LifeLevel.Modules.Map.Domain.Entities.UserMapProgress", null)
                        .WithMany()
                        .HasForeignKey("UserMapProgressId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("DungeonPortal");
                });

            modelBuilder.Entity("LifeLevel.Modules.Adventure.Encounters.Domain.Entities.Boss", b =>
                {
                    b.HasOne("LifeLevel.Modules.Map.Domain.Entities.MapNode", null)
                        .WithOne()
                        .HasForeignKey("LifeLevel.Modules.Adventure.Encounters.Domain.Entities.Boss", "NodeId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("LifeLevel.Modules.Adventure.Encounters.Domain.Entities.Chest", b =>
                {
                    b.HasOne("LifeLevel.Modules.Map.Domain.Entities.MapNode", null)
                        .WithOne()
                        .HasForeignKey("LifeLevel.Modules.Adventure.Encounters.Domain.Entities.Chest", "NodeId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("LifeLevel.Modules.Adventure.Encounters.Domain.Entities.UserBossState", b =>
                {
                    b.HasOne("LifeLevel.Modules.Adventure.Encounters.Domain.Entities.Boss", "Boss")
                        .WithMany("UserStates")
                        .HasForeignKey("BossId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("LifeLevel.Modules.Identity.Domain.Entities.User", null)
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("LifeLevel.Modules.Map.Domain.Entities.UserMapProgress", null)
                        .WithMany()
                        .HasForeignKey("UserMapProgressId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Boss");
                });

            modelBuilder.Entity("LifeLevel.Modules.Adventure.Encounters.Domain.Entities.UserChestState", b =>
                {
                    b.HasOne("LifeLevel.Modules.Adventure.Encounters.Domain.Entities.Chest", "Chest")
                        .WithMany("UserStates")
                        .HasForeignKey("ChestId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("LifeLevel.Modules.Identity.Domain.Entities.User", null)
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("LifeLevel.Modules.Map.Domain.Entities.UserMapProgress", null)
                        .WithMany()
                        .HasForeignKey("UserMapProgressId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Chest");
                });

            modelBuilder.Entity("LifeLevel.Modules.Character.Domain.Entities.Character", b =>
                {
                    b.HasOne("LifeLevel.Modules.Character.Domain.Entities.CharacterClass", "Class")
                        .WithMany()
                        .HasForeignKey("ClassId");

                    b.HasOne("LifeLevel.Modules.Identity.Domain.Entities.User", null)
                        .WithOne()
                        .HasForeignKey("LifeLevel.Modules.Character.Domain.Entities.Character", "UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Class");
                });

            modelBuilder.Entity("LifeLevel.Modules.Character.Domain.Entities.XpHistoryEntry", b =>
                {
                    b.HasOne("LifeLevel.Modules.Character.Domain.Entities.Character", null)
                        .WithMany()
                        .HasForeignKey("CharacterId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("LifeLevel.Modules.Identity.Domain.Entities.UserRingItem", b =>
                {
                    b.HasOne("LifeLevel.Modules.Identity.Domain.Entities.User", "User")
                        .WithMany("RingItems")
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("User");
                });

            modelBuilder.Entity("LifeLevel.Modules.Integrations.Domain.Entities.ExternalActivityRecord", b =>
                {
                    b.HasOne("LifeLevel.Modules.Character.Domain.Entities.Character", null)
                        .WithMany()
                        .HasForeignKey("CharacterId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("LifeLevel.Modules.Integrations.Domain.Entities.StravaConnection", b =>
                {
                    b.HasOne("LifeLevel.Modules.Identity.Domain.Entities.User", null)
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("LifeLevel.Modules.Items.Domain.Entities.CharacterItem", b =>
                {
                    b.HasOne("LifeLevel.Modules.Character.Domain.Entities.Character", null)
                        .WithMany()
                        .HasForeignKey("CharacterId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("LifeLevel.Modules.Items.Domain.Entities.Item", "Item")
                        .WithMany()
                        .HasForeignKey("ItemId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("Item");
                });

            modelBuilder.Entity("LifeLevel.Modules.Items.Domain.Entities.EquipmentSlot", b =>
                {
                    b.HasOne("LifeLevel.Modules.Character.Domain.Entities.Character", null)
                        .WithMany()
                        .HasForeignKey("CharacterId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("LifeLevel.Modules.Items.Domain.Entities.CharacterItem", "CharacterItem")
                        .WithMany()
                        .HasForeignKey("CharacterItemId")
                        .OnDelete(DeleteBehavior.SetNull);

                    b.Navigation("CharacterItem");
                });

            modelBuilder.Entity("LifeLevel.Modules.LoginReward.Domain.Entities.LoginReward", b =>
                {
                    b.HasOne("LifeLevel.Modules.Identity.Domain.Entities.User", null)
                        .WithOne()
                        .HasForeignKey("LifeLevel.Modules.LoginReward.Domain.Entities.LoginReward", "UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("LifeLevel.Modules.Map.Domain.Entities.MapEdge", b =>
                {
                    b.HasOne("LifeLevel.Modules.Map.Domain.Entities.MapNode", "FromNode")
                        .WithMany("EdgesFrom")
                        .HasForeignKey("FromNodeId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("LifeLevel.Modules.Map.Domain.Entities.MapNode", "ToNode")
                        .WithMany("EdgesTo")
                        .HasForeignKey("ToNodeId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("FromNode");

                    b.Navigation("ToNode");
                });

            modelBuilder.Entity("LifeLevel.Modules.Map.Domain.Entities.MapNode", b =>
                {
                    b.HasOne("LifeLevel.Modules.WorldZone.Domain.Entities.WorldZone", null)
                        .WithMany()
                        .HasForeignKey("WorldZoneId")
                        .OnDelete(DeleteBehavior.Restrict);
                });

            modelBuilder.Entity("LifeLevel.Modules.Map.Domain.Entities.UserMapProgress", b =>
                {
                    b.HasOne("LifeLevel.Modules.Map.Domain.Entities.MapEdge", "CurrentEdge")
                        .WithMany()
                        .HasForeignKey("CurrentEdgeId")
                        .OnDelete(DeleteBehavior.Restrict);

                    b.HasOne("LifeLevel.Modules.Map.Domain.Entities.MapNode", "CurrentNode")
                        .WithMany()
                        .HasForeignKey("CurrentNodeId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("LifeLevel.Modules.Map.Domain.Entities.MapNode", "DestinationNode")
                        .WithMany()
                        .HasForeignKey("DestinationNodeId")
                        .OnDelete(DeleteBehavior.Restrict);

                    b.HasOne("LifeLevel.Modules.Identity.Domain.Entities.User", null)
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("CurrentEdge");

                    b.Navigation("CurrentNode");

                    b.Navigation("DestinationNode");
                });

            modelBuilder.Entity("LifeLevel.Modules.Map.Domain.Entities.UserNodeUnlock", b =>
                {
                    b.HasOne("LifeLevel.Modules.Map.Domain.Entities.MapNode", "MapNode")
                        .WithMany()
                        .HasForeignKey("MapNodeId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("LifeLevel.Modules.Identity.Domain.Entities.User", null)
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("LifeLevel.Modules.Map.Domain.Entities.UserMapProgress", "UserMapProgress")
                        .WithMany("UnlockedNodes")
                        .HasForeignKey("UserMapProgressId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("MapNode");

                    b.Navigation("UserMapProgress");
                });

            modelBuilder.Entity("LifeLevel.Modules.Quest.Domain.Entities.UserQuestProgress", b =>
                {
                    b.HasOne("LifeLevel.Modules.Quest.Domain.Entities.Quest", "Quest")
                        .WithMany("UserProgress")
                        .HasForeignKey("QuestId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("LifeLevel.Modules.Identity.Domain.Entities.User", null)
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Quest");
                });

            modelBuilder.Entity("LifeLevel.Modules.Streak.Domain.Entities.Streak", b =>
                {
                    b.HasOne("LifeLevel.Modules.Identity.Domain.Entities.User", null)
                        .WithOne()
                        .HasForeignKey("LifeLevel.Modules.Streak.Domain.Entities.Streak", "UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("LifeLevel.Modules.WorldZone.Domain.Entities.UserWorldProgress", b =>
                {
                    b.HasOne("LifeLevel.Modules.WorldZone.Domain.Entities.WorldZoneEdge", "CurrentEdge")
                        .WithMany()
                        .HasForeignKey("CurrentEdgeId")
                        .OnDelete(DeleteBehavior.Restrict);

                    b.HasOne("LifeLevel.Modules.WorldZone.Domain.Entities.WorldZone", "CurrentZone")
                        .WithMany()
                        .HasForeignKey("CurrentZoneId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("LifeLevel.Modules.WorldZone.Domain.Entities.WorldZone", "DestinationZone")
                        .WithMany()
                        .HasForeignKey("DestinationZoneId")
                        .OnDelete(DeleteBehavior.Restrict);

                    b.HasOne("LifeLevel.Modules.Identity.Domain.Entities.User", null)
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("LifeLevel.Modules.WorldZone.Domain.Entities.World", "World")
                        .WithMany("UserProgresses")
                        .HasForeignKey("WorldId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("CurrentEdge");

                    b.Navigation("CurrentZone");

                    b.Navigation("DestinationZone");

                    b.Navigation("World");
                });

            modelBuilder.Entity("LifeLevel.Modules.WorldZone.Domain.Entities.UserZoneUnlock", b =>
                {
                    b.HasOne("LifeLevel.Modules.Identity.Domain.Entities.User", null)
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("LifeLevel.Modules.WorldZone.Domain.Entities.UserWorldProgress", "UserWorldProgress")
                        .WithMany("UnlockedZones")
                        .HasForeignKey("UserWorldProgressId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("LifeLevel.Modules.WorldZone.Domain.Entities.WorldZone", "WorldZone")
                        .WithMany("UnlockedByUsers")
                        .HasForeignKey("WorldZoneId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("UserWorldProgress");

                    b.Navigation("WorldZone");
                });

            modelBuilder.Entity("LifeLevel.Modules.WorldZone.Domain.Entities.WorldZone", b =>
                {
                    b.HasOne("LifeLevel.Modules.WorldZone.Domain.Entities.World", "World")
                        .WithMany("Zones")
                        .HasForeignKey("WorldId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("World");
                });

            modelBuilder.Entity("LifeLevel.Modules.WorldZone.Domain.Entities.WorldZoneEdge", b =>
                {
                    b.HasOne("LifeLevel.Modules.WorldZone.Domain.Entities.WorldZone", "FromZone")
                        .WithMany("EdgesFrom")
                        .HasForeignKey("FromZoneId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("LifeLevel.Modules.WorldZone.Domain.Entities.WorldZone", "ToZone")
                        .WithMany("EdgesTo")
                        .HasForeignKey("ToZoneId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("FromZone");

                    b.Navigation("ToZone");
                });

            modelBuilder.Entity("LifeLevel.Modules.Adventure.Dungeons.Domain.Entities.Crossroads", b =>
                {
                    b.Navigation("Paths");

                    b.Navigation("UserStates");
                });

            modelBuilder.Entity("LifeLevel.Modules.Adventure.Dungeons.Domain.Entities.DungeonPortal", b =>
                {
                    b.Navigation("Floors");

                    b.Navigation("UserStates");
                });

            modelBuilder.Entity("LifeLevel.Modules.Adventure.Encounters.Domain.Entities.Boss", b =>
                {
                    b.Navigation("UserStates");
                });

            modelBuilder.Entity("LifeLevel.Modules.Adventure.Encounters.Domain.Entities.Chest", b =>
                {
                    b.Navigation("UserStates");
                });

            modelBuilder.Entity("LifeLevel.Modules.Identity.Domain.Entities.User", b =>
                {
                    b.Navigation("RingItems");
                });

            modelBuilder.Entity("LifeLevel.Modules.Map.Domain.Entities.MapNode", b =>
                {
                    b.Navigation("EdgesFrom");

                    b.Navigation("EdgesTo");
                });

            modelBuilder.Entity("LifeLevel.Modules.Map.Domain.Entities.UserMapProgress", b =>
                {
                    b.Navigation("UnlockedNodes");
                });

            modelBuilder.Entity("LifeLevel.Modules.Quest.Domain.Entities.Quest", b =>
                {
                    b.Navigation("UserProgress");
                });

            modelBuilder.Entity("LifeLevel.Modules.WorldZone.Domain.Entities.UserWorldProgress", b =>
                {
                    b.Navigation("UnlockedZones");
                });

            modelBuilder.Entity("LifeLevel.Modules.WorldZone.Domain.Entities.World", b =>
                {
                    b.Navigation("UserProgresses");

                    b.Navigation("Zones");
                });

            modelBuilder.Entity("LifeLevel.Modules.WorldZone.Domain.Entities.WorldZone", b =>
                {
                    b.Navigation("EdgesFrom");

                    b.Navigation("EdgesTo");

                    b.Navigation("UnlockedByUsers");
                });
#pragma warning restore 612, 618
        }
    }
}
